#!/usr/bin/env bash
# This script displays the PID of your Bash process.

# shellcheck disable=SC2009
# Use the ps command to list processes and filter for the Bash process
ps aux | grep bash | grep -v grep
